services:
  ollama-server:
    image: ollama/ollama:0.5.13
    container_name: ollama-server
    restart: always
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.5.20
    container_name: open-webui
    restart: always
    environment:
      - 'OLLAMA_BASE_URL=http://ollama-server:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080"
    depends_on:
      - ollama-server

volumes:
  ollama:
  open-webui:
